# Generated by Django 4.2.6 on 2023-10-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(max_length=50, verbose_name='Formación')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('created', models.DateTimeField(verbose_name='Fecha de Creación')),
            ],
        ),
    ]
