# Generated by Django 4.2.6 on 2023-10-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academic',
            options={'ordering': ['-created'], 'verbose_name': 'académico', 'verbose_name_plural': 'académicos'},
        ),
        migrations.AlterField(
            model_name='academic',
            name='created',
            field=models.DateField(verbose_name='Fecha de Creación'),
        ),
    ]
